---
title: "Práctica 6"
author: "Cambios de Base"
output: pdf_document
---

Resolver los siguientes problemas

@. Considere las siguientes bases de $\mathbb{R}^{3}$, 
$\mathcal{B}=\{\mathtt{v}_1=(0,-2,3), \mathtt{v}_2=(0,1,1), \mathtt{v}_3=(1,1,0)\}$ y
$\mathcal{C}=\{\mathtt{v}_1=(0,-1,1), \mathtt{v}_2=(0,3,0), \mathtt{v}_3=(1,-1,1)\}$.

* Determinar la matriz cambio de base de $\mathcal{C}\rightarrow \mathcal{B}$

* Determinar la matriz cambio de base de $\mathcal{B} \rightarrow \mathcal{C}$.

* Si $\big(\mathtt{u}\big)_{\mathcal{C}}=(2,1,3)_{\mathcal{C}}$.

* Si $\big(\mathtt{v}\big)_{\mathcal{B}}=(-1,4,1)_{\mathcal{B}}$.

@. Sea $V=\mathbb{R}^3$ y sea $\mathcal{B}=\begin{Bmatrix}\begin{pmatrix} 1 \\ 1\\ 1 \end{pmatrix}, \begin{pmatrix} 1 \\ 1\\ 2 \end{pmatrix}, \begin{pmatrix} 1 \\ 2\\ 3 \end{pmatrix}  \end{Bmatrix}$, sea $\vec{r}=\begin{pmatrix} 6 \\ 9 \\ 14 \end{pmatrix}$, calcular las coordenadas en la base $\mathcal{B}$.

@. Sea $V=\mathbb{R}_2[x]$ el espacio de polinomios con grado $\leq 2$ y  $\mathcal{C}=\Big\{p_1(x)=1,\,\, p_2(x)=x,\,\,p_3(x)=x^2\Big\}$ y $\mathcal{B}'=\Big\{q_1(x)=x-1,\,\, q_2(x)=x^2+1,\,\, q_3(x)=x^2+x+1\Big\}$.

 * Calcular la matriz cambio de base $Q_{C\rightarrow B}$.
 
 * Usar el ejercicio anterior para expresar a 1 como combinación lineal de $x-1$, $x^2+1$ y $x^2+x+1$.
 
 * Expresar a $(x+1)^2$ como combinación lineal de $x-1$, $x^2+1$ y $x^2+x+1$.