---
title: "Tarea Matrices 2"
author: "Álgebra Lineal"
header-includes:
   - \usepackage{blindtext}
   - \usepackage{amsmath}
   - \usepackage{mathtools}
   - \usepackage{multicol}
geometry: "left=2cm,right=1cm,top=1cm,bottom=1.5cm"
output: pdf_document
---

# Álgebra de Matrices

1- Calcular
\begin{equation*}
\begin{array}{cccc}
  \begin{bmatrix} 
    2 & -3\\ 
    4 & -6
  \end{bmatrix} & \cdot 
    \begin{bmatrix} 
    9 & -6\\ 
    6 & -4
  \end{bmatrix} &\,\,\,\,\, &  
  \begin{bmatrix} 
    1 & -2\\ 
    3 & -4
  \end{bmatrix}^{3}
\end{array}
\end{equation*}


2- Sean 
 \begin{equation*}
\begin{array}{ccccc}
A= & 
  \begin{bmatrix} 
    1  & -1 & 1 \\ 
    2  & 0  & 1 \\
    3  & 0 & 1
  \end{bmatrix}   & \,\,\,\,\,\, & 
B = &  \begin{bmatrix} 
    2  & -2  \\ 
    1  & 3 \\
    4  & 4  
  \end{bmatrix} 
\end{array}
\end{equation*}

Verificar directamente que $A(AB) = A^2 B$

@. Calcular 

\begin{multicols}{3}

\begin{equation*}
\begin{pmatrix}
 1 & -2 \\ 3 & -4
\end{pmatrix}^3
\end{equation*}

\begin{equation*}
\begin{pmatrix}
4 & -1 \\ 5 & -2
\end{pmatrix}^5
\end{equation*}

\begin{equation*}
\begin{pmatrix}
2 & -1 \\ 3 & -2
\end{pmatrix}^n
\end{equation*}

\begin{equation*}
\begin{pmatrix}
1 & 1 \\ 0 & 1
\end{pmatrix}^n
\end{equation*}

\begin{equation*}
\begin{pmatrix}
\lambda & 1 \\ 0 & \lambda
\end{pmatrix}^n
\end{equation*}

\end{multicols}

@. 1- Si $p,q\in\mathbb{Z}$ tal que $pq \geq 1$, sea $A=\begin{pmatrix}\sqrt{pq-1} & -p \\ q & -\sqrt{pq-1} \end{pmatrix}$. Calcular $A^2$.
 2- Demostrar que la ecuación $A^2+I=0$ tiene una infinidad de soluciones.
 
@. Si $B=\begin{pmatrix} 2 & 1 \\ -1 & 0 \end{pmatrix}$, hallar $B^5$ y una fórmula general para $B^n$, probar que la fórmula es cierta por medio de inducción matemática.


# Matrices inversas

@. Encuentre la inversa de la matriz

\begin{equation}
  \begin{pmatrix}
    1 & 2 & 3 & 4 \\
    0 & 2 & 3 & 4 \\
    0 & 0 & 3 & 4 \\
    0 & 0 & 0 & 4
  \end{pmatrix}
\end{equation}

@. Generalize el problema para 

\begin{equation}
  A_5 = \begin{pmatrix}
          1 & 2 & 3 & 4 & 5 \\
          0 & 2 & 3 & 4 & 5 \\
          0 & 0 & 3 & 4 & 5 \\
          0 & 0 & 0 & 4 & 5 \\
          0 & 0 & 0 & 0 & 5 \\
        \end{pmatrix}
\end{equation}

@. Encontrar la inversa de matriz

\begin{equation}
  A_5 = \begin{pmatrix}
          1           & \frac{1}{2} & \frac{1}{3} & \frac{1}{4} \\
          \frac{1}{2} & \frac{1}{3} & \frac{1}{4} & \frac{1}{5} \\
          \frac{1}{3} & \frac{1}{4} & \frac{1}{5} & \frac{1}{6} \\
          \frac{1}{4} & \frac{1}{5} & \frac{1}{6} & \frac{1}{7}
        \end{pmatrix}
\end{equation}

@. Usando el método de Gauss-Jordan encontrar la inversa de 
\begin{equation}
  A= \begin{bmatrix} 
      1    & 0 & 0 & \ldots & 0 \\
      a_2  & 1 & 0 & \ldots & 0 \\
      a_3  & 0 & 1 & \ldots & 0 \\
    \vdots & \vdots & \ddots & \vdots \\
      a_{n-1} & 0 & 0 \ldots & 1
     \end{bmatrix}
\end{equation}

@. Calcular la inversa $A^{-1}$ de las siguientes matrices

\begin{multicols}{2}
a) 
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    -4 & -3\\ 
    -3 & 2
  \end{bmatrix}
\end{array}
\end{equation*}

b) 
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    0  & 1 \\ 
    1  & 1
  \end{bmatrix}
\end{array}
\end{equation*}

c) 
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    3  & 0 \\ 
    9  & 3
  \end{bmatrix}
\end{array}
\end{equation*}

d)
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    2  & 1 & 2 \\ 
    0  & 3 & -1 \\
    4  & 1 & 1
  \end{bmatrix}
\end{array}
\end{equation*}

e) 

\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    3  & 1 & -1 \\ 
    2  & 1 &  0 \\
    1  & 2 & 4
  \end{bmatrix}
\end{array}
\end{equation*}
\end{multicols}

@. Dadas las matrices $A=\begin{bmatrix} 5 & 3 \\ 3 & 2 \end{bmatrix}$, $B=\begin{bmatrix} 6 & 2 \\ 2 & 4 \end{bmatrix}$  y $C=\begin{bmatrix} 4 & -2 \\ -6 & 3 \end{bmatrix}$ resuelva cada una de las siguientes ecuaciones de matrices:
 a) $AX + B = C$.
 b) $XA + B = C$.
 c) $XA + C = X$.
  
@. Calcular $A+B$, $AB$, $A-B$, $A^{-1}$, $B^{-1}$ y $(AB)^{-1}$ si   
  
 \begin{equation*}
\begin{array}{ccccc}
A= & 
  \begin{bmatrix} 
    1  & 0 \\ 
    1  & 1
  \end{bmatrix}   & \,\,\,\,\,\, & 
B = &  \begin{bmatrix} 
    1  & 1 \\ 
    0  & 1
  \end{bmatrix} 
\end{array}
\end{equation*}

@. Sean 
 \begin{equation*}
\begin{array}{cccccccc}
A= & 
  \begin{bmatrix} 
    2  & 1 & 2 \\ 
    0  & 3 & -1 \\
    4  & 1 & 1
  \end{bmatrix}   & \,\,\,\,\,\, & 
B = &  \begin{bmatrix} 
    3   \\ 
    1   \\
    -1  
  \end{bmatrix} & \,\,\,\,\,\, &
C= & \begin{bmatrix} 
    1  & -1 & 1
  \end{bmatrix}
\end{array}
\end{equation*}

Calcular  $AB$, $CAB$, $B^{T}A^{T}C^{T}$, $CB$, $BC$, $AC^{T}B$, $CBA$.

@. Considere la siguiente matriz $A$ ¿para qué valores de $k$, la matriz es invertible?
\begin{equation*}
  \begin{bmatrix}
     k+3 & -1    &  1  \\
     5   & k-3   &  1\\
     6   & -6    & k+4
  \end{bmatrix}
\end{equation*}
@. Aplicando el método de Gauss-Jordan, mostrar que las siguientes matrices son no invertibles
\begin{equation*}
\begin{array}{cccc}
A= & 
  \begin{bmatrix} 
    4 & -3\\ 
    -8 & 6
  \end{bmatrix} \quad \quad
   &
A= & 
  \begin{bmatrix} 
    0  & 1 \\ 
    1  & 1
  \end{bmatrix}
\end{array}
\end{equation*}

@. Obtener la matriz escalonada reducida en función de $\alpha$ y $\beta$ para la matriz $A$, con eso, determinar los valores para los cuales $A$ es invertible

\[
A=\begin{bmatrix} 
      1      & 0 & \alpha \\ 
      0      &-1 &    0  \\
      \alpha &\beta & 0
  \end{bmatrix}
\]

@. Mostrar que para todo real $\theta$ la matriz es invertible y encontrar su inversa.
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    \sin(\theta)  & \cos(\theta)  & 0\\ 
    \cos(\theta)  & -\sin(\theta)  & 0\\
    0  & 0  & 1
  \end{bmatrix}
\end{array}
\end{equation*}

@. ¿Para que valores de $\lambda$ el sistema tiene solución única, infinidad de soluciones o ninguna solución?

\begin{multicols}{2}
\begin{equation*}
  \begin{array}{cccc}
     \lambda x   & + y   & + z    &= 1  \\
      x   & + \lambda y  & + z    & = 1\\
      x   & +  y  & +\lambda z    & =1
  \end{array}
\end{equation*}
\begin{equation*}
  \begin{array}{cccc}
     (1+\lambda) x   & + y   & + z    & = 1  \\
      x   & +(1+\lambda) y  & + z     & = \lambda  \\
      x   & +  y  & + (1+\lambda)z    & = \lambda^2
  \end{array}
\end{equation*}
\end{multicols}

@. Use el método de Gauss-Jordan para encontrar la inversa de la matriz o explicar por que no existe.

\begin{equation*}
\begin{array}{ccc}
  \begin{bmatrix} 
    1  & -1 & 2 \\ 
    3  & 1 & 2 \\
    2  & 3 & -1
  \end{bmatrix} & \,\,\,\,\,\, &
  \begin{bmatrix} 
    2  & 3 & 0 \\ 
    1  &-2 &-1 \\
    2  & 0 &-1
  \end{bmatrix} \\
    \begin{bmatrix} 
    1  & 1 & 0 \\ 
    1  & 0 & 1 \\
    0  & 1 & 1
  \end{bmatrix} & \,\,\,\,\,\, &
  \begin{bmatrix} 
    a  & 0 & 0 \\ 
    1  & a & 0 \\
    0  & 1 & a
  \end{bmatrix}
\end{array}
\end{equation*}

@. Demostrar que si $A$ es invertible y simérica entonces $A^{-1}$ también es simétrica.

@. Si $A$ es una matriz cuadrada de tamaño $n$, tal que $\mathbf{I}-A$ es invertible, probar que 
\[
A(\mathbf{I}-A)^{-1} = (\mathbf{I}-A)^{-1}A
\]

@. Calcular la matriz inversa de las siguientes matrices

\begin{multicols}{2}

\begin{equation*}
\begin{array}{ccc}
  \begin{bmatrix} 
    1  & a & a^2 & a^3 &\ldots & a^n\\ 
    0  & 1 & a   & a^2 &\ldots &a^{n-1} \\
    0  & 0 & 1   & a   &\ldots &a^{n-2} \\
    .  & . & .   & .   & \ldots & . \\
    0  & 0 & 0   & 0   & \ldots  & 1
  \end{bmatrix} & \,\,\,\,\,\, &
  \begin{bmatrix} 
    1  & 2 & 3 & \ldots & n-1 & n \\ 
    0  & 1 & 2 & \ldots & n-2 & n-1 \\
    .  & . & . & \ldots & .   & .  \\
    0  & 0 & 0 & \ldots & 1   & 2 \\
    0  & 0 & 0 & \ldots & 0   & 1 
  \end{bmatrix} \\
    \begin{bmatrix} 
    0  & 1 & 1 & \ldots & 1 \\ 
    1  & 0 & 1 & \ldots & 1 \\
    1  & 1 & 0 & \ldots & 1 \\
    .  & . & . & \ldots & . \\
    1  & 1 & 1 & \ldots & 1
  \end{bmatrix} & \,\,\,\,\,\, &
  \begin{bmatrix} 
    1+a  & 1  & 1 \\ 
    1    &1+a & 1 \\
    1    & 1  &1+a
  \end{bmatrix}
\end{array}
\end{equation*}

\end{multicols}

\vspace{0.5cm}

@. Resolver las ecuaciones

\begin{multicols}{2}

\begin{equation*}
\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}X =\begin{pmatrix} 3 & 5 \\ 5 & 9 \end{pmatrix}
\end{equation*}

\begin{equation*}
X\begin{pmatrix} 3 & -2 \\ 5 & -4 \end{pmatrix} =\begin{pmatrix} -1 & 2 \\ -5 & 6 \end{pmatrix}
\end{equation*}

\begin{equation*}
\begin{pmatrix} 1 & 2 & -3 \\ 3 & 2 &-4 \\ 2 & -1 & 0 \end{pmatrix}X =\begin{pmatrix} 1 & -3 & 0  \\ 10 & 2 & 7 \\ 10 & 7 & 8 \end{pmatrix}
\end{equation*}

\begin{equation*}
\begin{pmatrix} 2 & -3 & 1 \\ 4 & -5 & 2 \\ 5 & -7 & 3 \end{pmatrix}X
\begin{pmatrix} 9 & 7 & 6 \\ 1 & 1 & 2 \\ 1& 1 & 1 \end{pmatrix}
=\begin{pmatrix} 2 & 0 & -2  \\ 18 & 12 & 9 \\ 23 & 15 & 11 \end{pmatrix}
\end{equation*}

\end{multicols}

\newpage


# Matrices elementales

@. Sean 
\begin{equation*}
\begin{array}{ccccc}
A= &  
  \begin{bmatrix} 
    1  & 2 & -1 \\ 
    1  & 1 & 1 \\
    1  &-1 & 0
  \end{bmatrix}   & \,\,\,\,\,\, & 
B = &  \begin{bmatrix} 
    1  & -1 & 0 \\ 
    1  &  1 & 1 \\
    1  &  2 &-1  
  \end{bmatrix} 
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
C= &  
  \begin{bmatrix} 
    1  & 2 & -1 \\ 
    1  & 1 & 1 \\
    2  & 1 &-1
  \end{bmatrix}   & \,\,\,\,\,\, & 
B = &  \begin{bmatrix} 
    1  &  2 &-1 \\ 
   -3  & -1 & 3 \\
    2  &  1 &-1  
  \end{bmatrix} 
\end{array}
\end{equation*}

encontrar una matriz elemental $E$ que cumpla con lo siguiente

\begin{equation*}
\begin{array}{ccccc}
EA = B & \,\,\,\,\,\, & EB = A &\,\,\,\,\,\, & EA = C\\
EC = A & \,\,\,\,\,\, & EC = D &\,\,\,\,\,\, &
\end{array}
\end{equation*}



 19- Expresar a $A$ como un producto de matrices elementales
\begin{equation*}
\begin{array}{ccccc}
A= &  
  \begin{bmatrix} 
    2  & 1 & 2 \\ 
    4  & 3 & 2 \\
    1  & 1 & 1
  \end{bmatrix}   & \,\,\,\,\,\, & 
B = &  \begin{bmatrix} 
    1  & -3 & 2 \\ 
    4  &-2  & 1 \\
    1  &4   & 1  
  \end{bmatrix} 
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
C = &  
  \begin{bmatrix} 
    1  &  2 & 0 \\ 
    0  &  1 & 3 \\
    3  &  8 & 7
  \end{bmatrix}   & \,\,\,\,\,\, & 
D = &  \begin{bmatrix} 
    2  & 6  \\ 
    4  & -7 
  \end{bmatrix} 
\end{array}
\end{equation*}

# Factorización LU

@. Obtener la factorización $LU$ de las siguientes matrices.

\begin{equation*}
\begin{array}{ccccc}
 &  
  \begin{bmatrix} 
    1  & 3 \\ 
    2  & 7 
  \end{bmatrix}   & \,\,\,\,\,\, & 
 &  \begin{bmatrix} 
    1  & 1 & 0 \\ 
    0  & 1 & 1 \\
    1  & 1 & 1  
  \end{bmatrix} 
\end{array}
\end{equation*}


@. Encontrar la factorización $LU$ de cada una de las siguientes matrices
\begin{equation*}
\begin{array}{ccccccccccc}
$a$ &  
  \begin{bmatrix} 
    1  & -1& -1 \\ 
    3  & 4 & -2 \\
    2  &-3 & -2
  \end{bmatrix}   & \,\,\,\,\,\, & 
$b)$ &  \begin{bmatrix} 
    1  & 3 & -1 \\ 
    2  & 5 & 1 \\
    3  & 4 & 2  
  \end{bmatrix}  & \,\,\,\,\,\, &
$c)$ &  \begin{bmatrix} 
    2  & 3 & 6 \\ 
    4  & 7 & 9 \\
    3  & 5 & 4  
  \end{bmatrix} & \,\,\,\,\,\, &
$d)$ &  \begin{bmatrix} 
    1  & 2 & 3 \\ 
    2  & 4 & 7 \\
    3  & 7 & 10  
  \end{bmatrix}
\end{array}
\end{equation*}


@. Sea $A$ la matriz de $a)$ del problema anterior. Encontrar $X_1,X_2,X_3,X_4$ en donde
\begin{description}
\item{a)} $X_1$ es la solución de $AX_1 = b_1$ con $b_1=(1,1,1)^{T}$.
\item{b)} Para $k=2,3,4$, $X_k$ es la solución de $AX_{k}=b_k$ con $b_k=b_{k-1} + X_{k-1}$ 
\end{description}



# Regla de Cramer

1. Usa la regla de Cramer para resolver los siguientes sistemas de
ecuaciones:

\begin{multicols}{2}
\begin{equation*}
\begin{array}{cccccc}
x & + y &+ z &- w & = & 2  \\
  &   y &- z &+w  & = & 1  \\
  &     &  z &-w  & = & 0  \\
  &     &  z &+2w & = & 3
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
x & +y & +z & = & a \\
  & y  & +z & = & 0 \\
  &    & z  & = & 1 \\
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
x & + y &+ z  & = & 11  \\
2x& -6y &- z  & = & 0  \\
3x& +4y &+2z  & = & 0  
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
x & +2y & +3z & = & 7 \\
2x& +y  & +2z & = & 0 \\
-2x&+y  & -z  & = & 4 
\end{array}
\end{equation*}
\end{multicols}

2. Usando la fórmula de la adjunta calcula la inversa de las siguientes
matrices:

\begin{multicols}{2}
\begin{equation*}
\begin{array}{ccccc}
1) A=& 
  \begin{pmatrix} 
    -2       & 3      & 2           \\ 
     6       & 0      & 3           \\
     4       & 1      & -1     
  \end{pmatrix}
 & \,\,\,\,\, &
2) B=&  \begin{pmatrix} 
     \cos\theta       & 0      & -\mbox{sen}\theta    \\ 
       0              & 1      & 0           \\
    \mbox{sen}\theta  & 0      & \cos\theta     
  \end{pmatrix}
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
3) A=& 
  \begin{vmatrix} 
     1       & 2      & -1           \\ 
     0       & 1      & 3           \\
     2       & 3      & -3     
  \end{vmatrix}
 & \,\,\,\,\, &
4) A=&  \begin{vmatrix} 
     2       & 4      & -1           \\ 
     1       & -1     & 3           \\
     3       & 4      & -3   
  \end{vmatrix}
\end{array}
\end{equation*}
\end{multicols}

3. Determinar las condiciones sobre $a)$ y $b)$ tal que el sistema
\begin{equation*}
  \begin{array}{cccc}
     x   & + y   & -a z    &= 1  \\
     2 x & +3 y  & 2z      & = b\\
     x   & -y    & +bz     & =a
  \end{array}
\end{equation*}

4. Aplicando la regla de Cramer, indica todos los valores de $a$
tales que la solución del siguiente sistema \emph{no} sea única.
\begin{equation*}
\begin{array}{cccccc}
(8-a)x & +2y      & +3z & +aw  & = & 0 \\
     x & +(9-a)y  & +4z & + aw & = & 0 \\
     x & +2y      & +3z & + aw & = & 0 \\
     x & +2y      & +3z & + aw & = & 0
\end{array}
\end{equation*}

Para el siguiente sistema de ecuaciones lineales 
\begin{equation*}
  \begin{array}{cccccc}
       x_1 & -  & 2x_2 & +  &  ax_3    & = 1  \\
     3 x_1 & +  & 2x_2 & +  &  x_3    & = 2\\
     2 x_1 &    &      &  + &  ax_3    & = 3
  \end{array}
\end{equation*}

a) Usando la regla de Cramer, resolver el sistema para $a = 2$

b) Encontrar los valores para los cuales el sistema tiene una infinidad de soluciones.





