---
title: "Tarea 1"
header-includes:
   - \usepackage{blindtext}
   - \usepackage{amsmath}
   - \usepackage{mathtools}
   - \usepackage{multicol}
geometry: "left=2cm,right=1cm,top=1cm,bottom=1.5cm"
author: "álgebra lineal"
date: "2024-09-14"
output:
  pdf_document
  
---
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

# Vectores 

1. Una partícula tiene una posición en el tiempo de acuerdo a un movimiento rectilíneo uniforme dado por
$\vec{\mathbf{r}}(t) = 6t\hat{\mathbf{\iota}} + (8t+2)\hat{\mathbf{\jmath}}+(2t+1)\hat{\mathbf{k}}$. Suponga que a partir del tiempo $t=0$ se observa su desplazamiento

  a) ¿Cúal es la posición de la partícula después de 4 segundos?

  b) Calcular a que distancia del origen se encuentra la partícula al segundo 5.
  
  c) Si la rápidez de la partícula se calcula como $|\vec{v}|=\sqrt{v_x^2+v_y^{2}+v_z^{2}}$. Calcular la rapidez que tiene la partícula en el instante $t=4$.
  
1. Investigar el concepto de _cosenos_ _directores_. Calcular los cosenos directores de los siguientes vectores $\vec{\mathbf{a}}=(12,-15,-16)$,  $\vec{\mathbf{a}} = (2,-3,-1)$ y $\vec{\mathbf{a}} = (3, 4, 5)$
 
1. Sean $\vec{\mathbf{a}}=(3,-1,2,4)$, $\vec{\mathbf{b}}=(1,2,0,1)$, $\vec{\mathbf{c}}=(3,2,-3,5)$ y $\vec{\mathbf{d}}=(7,-4,1,11)$. Mostrar que $\vec{\mathbf{ab}}$ es paralelo a $\vec{\mathbf{cd}}$.    

1. Sea $\vec{\mathbf{a}}=(3,-1,4)$ y $\vec{\mathbf{b}}=(4,2,-1)$. Encontrar 
  $a)\quad\|\vec{\mathbf{a}} + \vec{\mathbf{b}}\|\quad\quad\quad b)\quad \|\vec{\mathbf{a}} - \vec{\mathbf{b}}\|\quad\quad\quad c)\quad \|2\vec{\mathbf{a}}-\vec{\mathbf{b}}\|$.

1. Encontrar un vector $\vec{\mathbf{x}}$, $\vec{\mathbf{x}}\ne \vec{\mathbf{0}}$ que sea ortogonal a $\vec{v}=(1,3,2)$. Encuentra una condición que cumplan todos los vectores ortogonales al vector $\vec{v}$. (_sugerencia_: en este caso, el vector $\vec{v}$ es un vector normal). 
 
1. Sean $\vec{A}=(5,3,3)$, $B=(1,3,1)$ y $C=(2,6,-1)$. Uno de los ángulos del tríangulo $ABC$ es recto. ¿qué ángulo es?

1. Escribir una condición para caracterizar a todos los vectores $\vec{\mathbf{x}}\in\mathbb{R}^{3}$ que sean ortogonales a los vectores $\vec{\mathbf{a}}=(1,3,2)$, $\vec{\mathbf{b}}=(-1,-2,1)$ y $\vec{\mathbf{c}}=(0,1,4)$. 

## Axiomas de Espacio vectorial

1. Demostrar que $\mathbb{R}^3$ con las operaciones de suma de vectores $+:\mathbb{R}^3\times \mathbb{R}^3\rightarrow \mathbb{R}^3$ y multiplicación escalar $\cdot:\mathbb{R}\times \mathbb{R}^3\rightarrow \mathbb{R}^{3}$ cumple los axiomas de espacio vectorial.


# Producto escalar en $\mathbb{R}^n$

1. Probar usando la definición de la norma euclidiana que para todo $c\in\mathbb{R}$ y $\vec{x}\in \mathbb{R}^n$, $\|c\cdot \vec{x}\|=|c|\|\vec{x}\|$.

1. Probar que $(a\vec{v}+b\vec{w})\boldsymbol{\cdot}(c\vec{v}+d\vec{w}) = ac\|\vec{v}\|^2 + (ad+bc)(\vec{v}\boldsymbol{\cdot}\vec{w})+bd\|\vec{w}\|^2$, para todo $a,b,c,d\in \mathbb{R}$ y $\vec{v},\vec{w}\in\mathbb{R}^n$

1. Probar la identidad de _polarización_. Para todo $\vec{v},\vec{w}\in\mathbb{R}^n$
\[
\vec{v}\boldsymbol{\cdot}\vec{w}=\frac{1}{4}(\|\vec{v}+\vec{w}\|^2-\|\vec{v}-\vec{w}\|^2)
\]

1. En $\mathbb{R}^2$, graficar el conjunto $D=\{\vec{v}\in\mathbb{R}^2\,:\, \|\vec{v}\|=1\}$.

1. Encontrar $a$ tal que $\vec{v}=(2,a,-3)$ sea ortogonal a $\vec{w}=(-1,3,-2)$



# Rectas y planos

1. Encontrar las ecuaciones vectorial y paramétricas del plano que pasa por $A=(-1,2,2)$, $B=(0,3,1)$ y $C=(0,0,2)$.

1. Determinar la ecuación del plano que pasa por $A=(1,0,4)$ que es ortogonal a la línea que pasa por el origen y  $(2,3,4)$

1. Escribir la ecuación del plano que pasa por el punto $(3,7,2)$ y es paralelo a las rectas $l_1:$
 $\frac{x-1}{4}=\frac{y+2}{1}=\frac{z-4}{2}$ y $l_2:$ $\frac{x-3}{5}=\frac{y-2}{3}=\frac{z+1}{1}$
 
1. Escribir la ec. del plano que pasa por $(1,0,-1)$ y  contiene a la recta $\frac{x}{2}=\frac{y+1}{3}=\frac{z-2}{1}$.

1. Sea $E$ el conjunto de vectores en $\mathbb{R}^{3}$ que son ortogonales a $(3,2,1)$. Mostrar que $E$ es un plano encontrando su ecuación.
  
1. Sea $E$ el conjunto de puntos de la forma
  \[
  \{ \vec{\mathbf{v}} \in \mathbb{R}^{3} \,:\, \vec{\mathbf{v}} = (3,2,1) + s (2,0,1) + t(1,1,2), s,t\in\mathbb{R}   \}
  \]
Mostrar que $E$ es un plano y encontrar su ecuación cartesiana.

1. Sea $E$ el plano con ecuación $x+y-2z=3$. Si $l$ es la recta con ecuación $X(t)=(2,1,3) + t(0,1,4)$. Hallar la intersección de la recta y el plano.

1. Sea $\vec{A}=(-1,2,3)$, $\vec{B}=(2,5,-3)$, $\vec{C}=(4,1,-1)$ y $\vec{D}=(1,3,-3)$.

  a) Encuentre el vector de los puntos de trisección de la recta que pasa por $\vec{A}$ y $\vec{B}$.
  
  b) Encuentre la distancia entre los puntos $A$ y $B$.
  
  d) Encontrar la ecuación del plano que pasa por $\vec{A}$ y perpendicular a $\vec{OB}$.
  
  e) Encontrar la ecuación del plano que pasa por el origen $\textbf{O}$ y los puntos $\vec{A}$ y $\vec{B}$.
  
  f) Encontrar la distancia de $\vec{OD}$ al plano formado por $A,B\,\mbox{ y } C$. _Sugerencia_: revisar la fórmula o bien calcular la recta que pasa por $OD$ y dirección $\vec{d}=\vec{n}$.
  
  g) Encontrar la ecuación vectorial (paramétrica) que pasa por $\vec{A}$ y paralelo a $\vec{BC}$.
  
  h) Encontrar la ecuación de la recta que pasa por $\vec{D}$ y forma un ánuglo de $30°$ con la normal al plano formado por $ABC$.

9. Se dan los vértices de un triángulo en $A=(0,0,0)$, $B=(0,4,4)$ y $C=(3,3,0)$.
 
 i) Calcular los ángulos internos en cada vértice y  el perímetro del triángulo

 ii) Calcular el plano que contiene al triángulo.
 
 iii) Encontrar el conjunto intersección del plano en ii) y el plano $2x-y-2z=4$

\newpage
# Sistemas de ecuaciones

1. Considere los siguientes sistemas de ecuaciones lineales:
\[
\begin{array}{cc}
  2x_1 + 3x_2 &= 5 \\
  x_1  - 4x_2 &= -3 \\
  2x_1 - 8x_2 & = -6
\end{array} 
\quad \quad \quad
\begin{array}{cc}
  2x_1 + 3x_2 &= 5 \\
  x_1  - 4x_2 &= -3 
\end{array}
\]
Determine el conjunto solución de cada uno de los sistemas ¿Son sistemas equivalentes?

2. Encontrar todos los vectores en $\mathbb{R}^3$ que sean ortogonales a $(1,2,3)$ y a $(-2,0,1)$.

3. Usar eliminación gaussiana para resolver los siguientes sistemas

\begin{multicols}{2}
\begin{equation*}
  \begin{array}{cccc}
     x_1   & + x_2  & + x_3  & = 1  \\
     x_1   & + 2x_2 & +2x_3  & = 1  \\
     x_1   & + 2x_2 & +3x_3  & = 1
  \end{array}
\end{equation*}

\begin{equation*}
  \begin{array}{cccc}
     2x_1  & - x_2  &       & = 0  \\
     -x_1  & + 2x_2 & -x_3  & = 0  \\
           & - x_2 & + x_3  & = 1
  \end{array}
\end{equation*}
\begin{equation*}
  \begin{array}{cccc}
            &   4x_2  & -3 x_3  & = 3  \\
     -x_1   & + 7x_2  & -5x_3   & = 4  \\
     -x_1   & + 8x_2  & -6x_3   & = 5
  \end{array}
\end{equation*}

\begin{equation*}
  \begin{array}{ccccc}
     x_1   & + x_2  & +x_3  &+x_4   & = 1  \\
     x_1   & + x_2  & +3x_3 &+3x_4  & = 3  \\
     x_1   & + x_2  & +2x_3 &+3x_4  & = 3  \\
     x_1   & +3x_2  & +3x_3 &+3x_4  & = 4
  \end{array}
\end{equation*}
\end{multicols}


4. Determinar el valor de $\lambda$ para que el siguiente sistema de ecuaciones tenga soluciones no nulas (y de hecho una infinidad).

\begin{equation*}
  \begin{array}{cccc}
     x_1   & + 2x_2   & -2 x_3        & = 0  \\
     2x_1  & - x_2    & +\lambda x_3  & = 0\\
     3x_1  & + x_2    & -x_3z           & = 0
  \end{array}
\end{equation*}

5. Encontrar las soluciones del sistema de ecuaciones

\begin{multicols}{2}
\begin{equation}
  \begin{array}{cccc}
     x_1   & + x_2   & +x_5    &= 0  \\
     x_1   & + x_2   & -x_3    & = 0\\
     x_3   & + x_4   & +x_5    & = 0
  \end{array}
\end{equation}\quad

\begin{equation}
  \begin{array}{cccc}
     x_1   & + x_2   & -x_3    &= 2  \\
     x_1   & -3 x_2   & +3x_3    & = 0\\
     2x_1   & + x_2   & +x_3    & = 6
  \end{array}
\end{equation}
\begin{equation}
  \begin{array}{cccc}
     x_1   & + x_2   & -x_3    &= 0  \\
     2x_1  & +2 x_2   & -x_3    & = 2\\
     -x_1   & - x_2   & +x_3    & = 0
  \end{array}
\end{equation}

\begin{equation}
  \begin{array}{ccccl}
     x_1   & + x_2    & -2x_3 & +x_4    &= 3  \\
     2x_1  & +2 x_2   & +x_3  &-3x_4    & = 1\\
     x_1   & - 2x_2    & +x_3 &+x_4     & = 3 \\
     x_1   & - x_2    & -x_3 &+2x_4     & = 4 
  \end{array}
\end{equation}
\end{multicols}

6.Determinar el valor de $\lambda$ para que el siguiente sistema de ecuaciones tenga una infinidad de soluciones. ¿En que casos no tiene solución?

\begin{equation*}
  \begin{array}{cccccc}
     x_1        & + & 2x_2  & - & 2 x_3            & = 0  \\
    2x_1        & - &  x_2  & + &  \lambda x_3     & = 0\\
    3x_1        & + &  x_2  & - & \lambda  x_3     & = 0
  \end{array}
\end{equation*}

7.Para las siguientes matrices:
\begin{itemize}
\item Usando eliminación gaussiana encontrar su forma escalonada reducida. 
\item Escribir el sistema de ecuaciones resultante $Ax=0$.
\item Resolver el sistema de ecuaciones y expresar el conjunto solución.
\end{itemize}

\begin{equation*}
\begin{array}{ccccc}
A =& \begin{bmatrix} 
      2  & 3 & 6 \\ 
      4  & 7 & 9 \\
      3  & 5 & 4  
     \end{bmatrix} & \,\,\, &
B= & \begin{bmatrix} 
      1   & -2 & 1 & 0\\ 
      -2  &  4 & 0 & 2\\
      -1  &  2 & 1 & 2  
     \end{bmatrix}
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
C = & \begin{bmatrix} 
      1  &-2 & 1 & 0 \\ 
     -2  & 4 & 0 & 2\\
     -1  & 2 & 1 & 2  
     \end{bmatrix} & \,\,\, &
D = & \begin{bmatrix} 
      1   &  0 & 3 \\ 
      0   &  1 & -1\\
      -1  &  1 & -4  
     \end{bmatrix}
\end{array}
\end{equation*}

8. Encuentra los posibles valores para $h$ y $k$ tales que el sistema con matriz aumentada

\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    1  & 2 \bigm| & h \\ 
    2  & k \bigm| &12   
  \end{bmatrix}   
\end{array}
\end{equation*}

tenga solución única.


# Matrices

1. Calcula los productos $ABC$ y $BA$ de las matrices, con 
\[
\begin{array}{lcr}
A=\begin{pmatrix}
    991 & 992 & 993 \\
    994 & 995 & 996 \\
    997 & 998 & 999
  \end{pmatrix}, \quad &
B = \begin{pmatrix}
    12 & -6 & -2 \\
    18 & -9 & -3 \\
    24 &-12 & -4
    \end{pmatrix}, \quad &
C = \begin{pmatrix}
    1 & 1  \\
    1 & 2  \\
    3 & 0 
    \end{pmatrix}
\end{array}
\]

1. a) Una matriz se dice *idempotente* si $A^2 = A$. Probar que
\[
B= \begin{pmatrix}
    2 & -3 & -5 \\
   -1 &  4 & 5  \\
    1 & -3 &- 4
   \end{pmatrix}
\]
es idempotente
 b) Demuestre qu si $A$ es idempotente, entonces $B=I_n-A$ también es idempotente,
 c) Si $A$ y $B$ son como en b) entonces demuestre que $AB= BA = \mathbf{0}$ 

2. Se dice que una matriz $n\times n$ es *involutiva* si y sólo si $A^2 = I_n$.
  
  a) Verifica que $A=\begin{pmatrix} 0 & 1 & -1 \\ 4 & -3 & 4 \\ 3 & -3 & 4 \end{pmatrix}$ es involutiva
  
  b) Demuestre que si $A$ es involutiva entonces $\frac{1}{2}(I_n+A)$ y $\frac{1}{2}(I_n-A)$ son idempotentes y su producto es igual a la matriz cero.
  
3. Para las siguientes matrices, encontrar la fórmula para $A^{n}$ con $n\in\mathbb{N}$,

\[
\begin{array}{cr}
 A= \begin{pmatrix}
    \cos x       & -\mbox{sen} x \\
    \mbox{sen} x & \cos x
    \end{pmatrix}, &
A= \begin{pmatrix}
    a       & 1 \\
    0       & a
    \end{pmatrix} 
\end{array}
\]

4. En $\mathbb{R}^3$ la matriz 
\[
 R_z(\phi)= \begin{pmatrix}
            \cos \phi       & -\mbox{sen} \phi & 0 \\
            \mbox{sen}\phi  & \cos \phi        & 0 \\
            0               &      0           & 1
    \end{pmatrix},
\]

a) Calcular $R_z(\phi)\vec{x}$ y  exlicar rota al vector $\vec{x}$ alrededor del eje $z$.)

b) Demuestre que si $\vec{v}' = R_z(\phi)\vec{v}$ entonces $\|\vec{v´}\|=\|\vec{v}\|$

5. Dada la matriz $\mathbf{X} =\begin{pmatrix} 0 & 2 \\ -1 & 0 \end{pmatrix}$ encontrar todas las matrices $\mathbf{Y}$ tales que $\mathbf{X}\mathbf{Y} = \mathbf{Y}\mathbf{X}$

6. El _conmutador_ de dos matrices cuadradas $A$ y $B$  se define como
\[
\big[A,B\big] = AB - BA
\]

a) Mostrar que las matrices conmutan con la multiplicación si $\big[A,B\big] = \mathbf{0}$

b) Calcular el conmutador de las siguientes matrices

 * $A=\begin{pmatrix} 1 & 0 \\1 & -1\end{pmatrix},\quad B=\begin{pmatrix} 2 & 1 \\-2 & 0\end{pmatrix}$ 
 
 *  $A=\begin{pmatrix} -1 & 3 \\ 3 & -1\end{pmatrix},\quad B=\begin{pmatrix} 1 & 7 \\-2 & 0\end{pmatrix}$ 

c) Demostrar que $\big[A,I\big] = \mathbf{0}$ para toda $A$ matriz $n\times n$


7. Calcular $M^2$, $M^3$ si $M$ está dada por
\[
M= \begin{pmatrix}
             0   & 0 & 0 & 0 \\
            3    & 0 & 0 & 0 \\
            1    & -1& 0 & 0 \\
            -1   & 2& 1 & 0   
    \end{pmatrix}, \quad
M= \begin{pmatrix}
             1   & 0 & 0 & 0 \\
            3    & 1 & 0 & 0 \\
            1    & -1& 1 & 0 \\
            -1   & 2& 1 & 1   
    \end{pmatrix}
\]

1. Si $A=\begin{pmatrix} 1 & 2 \\ -1 & 0 \end{pmatrix}$ calcular $A^5$.

1. Calcular $(ABC)^{-1}$ aplicando las propiedades de las matrices inversas
\[
A= \begin{pmatrix} 1 & 2 \\ 0 & 1 \end{pmatrix},\quad\quad B= \begin{pmatrix} 2 & 5 \\ 3 & 7 \end{pmatrix}\quad \mbox{ y } \quad 
C= \begin{pmatrix} 3 & 2 \\ 4 & 2\end{pmatrix}
\]


1. Si $A=\begin{pmatrix} 0 & 1 \\ -1 & 0 \end{pmatrix}$ calcular $A^{1000}$.

1. Si $\begin{pmatrix} 1 & 2 \\ 2 & -1 \end{pmatrix}$ calcular $B^{1000}$.

1. Calcular $A=\begin{pmatrix} 1 & 1 \\ 0 & 1 \end{pmatrix}$ 
  
  * calcular $A^2$.
    
  * calcular $A^3$.
    
  * calcular $A^{k}$. _observe_ _un_ _patrón_ _y_ _aplique_ _inducción_ _matemática_.

1. Para $\begin{pmatrix} 1/2 & \alpha \\ 0 & 1/2 \end{pmatrix}$ determinar para que casos de $\alpha$ existe el límite $\lim_{n\rightarrow \infty} A^{n}$. (_sugerencia_: _determinar_ _algunas_ _potencias_ _de_ $A^n$)

1. Sea $\vec{\mathbf{e}}_j$ el vector unitario $j$, el cual contiene en la j-ésima posición a 1 y en las demás coordenadas es igual a 0. Para una matrix $A$ describir los siguientes productos 

 a) $A\cdot e_j$      b) $e_i^T\cdot A$     c) $e_i^T\cdot A\cdot e_j$

# Matrices inversas

1. Encuentre la inversa de la matriz

\begin{equation}
  \begin{pmatrix}
    1 & 2 & 3 & 4 \\
    0 & 2 & 3 & 4 \\
    0 & 0 & 3 & 4 \\
    0 & 0 & 0 & 4
  \end{pmatrix}
\end{equation}

2. Generalize el problema para 

\begin{equation}
  A_5 = \begin{pmatrix}
          1 & 2 & 3 & 4 & 5 \\
          0 & 2 & 3 & 4 & 5 \\
          0 & 0 & 3 & 4 & 5 \\
          0 & 0 & 0 & 4 & 5 \\
          0 & 0 & 0 & 0 & 5 \\
        \end{pmatrix}
\end{equation}

3. Encontrar la inversa de matriz

\begin{equation}
  A_5 = \begin{pmatrix}
          1           & \frac{1}{2} & \frac{1}{3} & \frac{1}{4} \\
          \frac{1}{2} & \frac{1}{3} & \frac{1}{4} & \frac{1}{5} \\
          \frac{1}{3} & \frac{1}{4} & \frac{1}{5} & \frac{1}{6} \\
          \frac{1}{4} & \frac{1}{5} & \frac{1}{6} & \frac{1}{7}
        \end{pmatrix}
\end{equation}

4. Usando el método de Gauss-Jordan encontrar la inversa de 
\begin{equation}
  A= \begin{bmatrix} 
      1    & 0 & 0 & \ldots & 0 \\
      a_2  & 1 & 0 & \ldots & 0 \\
      a_3  & 0 & 1 & \ldots & 0 \\
    \vdots & \vdots & \ddots & \vdots \\
      a_{n-1} & 0 & 0 \ldots & 1
     \end{bmatrix}
\end{equation}

5. Calcular la inversa $A^{-1}$ de las siguientes matrices

\begin{multicols}{2}
a) 
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    -4 & -3\\ 
    -3 & 2
  \end{bmatrix}
\end{array}
\end{equation*}

b) 
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    0  & 1 \\ 
    1  & 1
  \end{bmatrix}
\end{array}
\end{equation*}

c) 
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    3  & 0 \\ 
    9  & 3
  \end{bmatrix}
\end{array}
\end{equation*}

d)
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    2  & 1 & 2 \\ 
    0  & 3 & -1 \\
    4  & 1 & 1
  \end{bmatrix}
\end{array}
\end{equation*}

e) 

\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    3  & 1 & -1 \\ 
    2  & 1 &  0 \\
    1  & 2 & 4
  \end{bmatrix}
\end{array}
\end{equation*}
\end{multicols}

6. Dadas las matrices $A=\begin{bmatrix} 5 & 3 \\ 3 & 2 \end{bmatrix}$, $B=\begin{bmatrix} 6 & 2 \\ 2 & 4 \end{bmatrix}$  y $C=\begin{bmatrix} 4 & -2 \\ -6 & 3 \end{bmatrix}$ resuelva cada una de las siguientes ecuaciones de matrices:
 a) $AX + B = C$.
 b) $XA + B = C$.
 c) $XA + C = X$.
  
7. Calcular $A+B$, $AB$, $A-B$, $A^{-1}$, $B^{-1}$ y $(AB)^{-1}$ si   
  
 \begin{equation*}
\begin{array}{ccccc}
A= & 
  \begin{bmatrix} 
    1  & 0 \\ 
    1  & 1
  \end{bmatrix}   & \,\,\,\,\,\, & 
B = &  \begin{bmatrix} 
    1  & 1 \\ 
    0  & 1
  \end{bmatrix} 
\end{array}
\end{equation*}

8. Sean 
 \begin{equation*}
\begin{array}{cccccccc}
A= & 
  \begin{bmatrix} 
    2  & 1 & 2 \\ 
    0  & 3 & -1 \\
    4  & 1 & 1
  \end{bmatrix}   & \,\,\,\,\,\, & 
B = &  \begin{bmatrix} 
    3   \\ 
    1   \\
    -1  
  \end{bmatrix} & \,\,\,\,\,\, &
C= & \begin{bmatrix} 
    1  & -1 & 1
  \end{bmatrix}
\end{array}
\end{equation*}

Calcular  $AB$, $CAB$, $B^{T}A^{T}C^{T}$, $CB$, $BC$, $AC^{T}B$, $CBA$.

9. Considere la siguiente matriz $A$ ¿para qué valores de $k$, la matriz es invertible?
\begin{equation*}
  \begin{bmatrix}
     k+3 & -1    &  1  \\
     5   & k-3   &  1\\
     6   & -6    & k+4
  \end{bmatrix}
\end{equation*}
10. Aplicando el método de Gauss-Jordan, mostrar que las siguientes matrices son no invertibles
\begin{equation*}
\begin{array}{cccc}
A= & 
  \begin{bmatrix} 
    4 & -3\\ 
    -8 & 6
  \end{bmatrix} \quad \quad
   &
A= & 
  \begin{bmatrix} 
    0  & 1 \\ 
    1  & 1
  \end{bmatrix}
\end{array}
\end{equation*}


11. Mostrar que para todo real $\theta$ la matriz es invertible y encontrar su inversa.
\begin{equation*}
\begin{array}{cc}
A= & 
  \begin{bmatrix} 
    \sin(\theta)  & \cos(\theta)  & 0\\ 
    \cos(\theta)  & -\sin(\theta)  & 0\\
    0  & 0  & 1
  \end{bmatrix}
\end{array}
\end{equation*}

12. ¿Para que valores de $\lambda$ el sistema tiene solución única, infinidad de soluciones o ninguna solución?

\begin{multicols}{2}
\begin{equation*}
  \begin{array}{cccc}
     \lambda x   & + y   & + z    &= 1  \\
      x   & + \lambda y  & + z    & = 1\\
      x   & +  y  & +\lambda z    & =1
  \end{array}
\end{equation*}
\begin{equation*}
  \begin{array}{cccc}
     (1+\lambda) x   & + y   & + z    & = 1  \\
      x   & +(1+\lambda) y  & + z     & = \lambda  \\
      x   & +  y  & + (1+\lambda)z    & = \lambda^2
  \end{array}
\end{equation*}
\end{multicols}

13. Use el método de Gauss-Jordan para encontrar la inversa de la matriz o explicar por que no existe.
\begin{equation*}
\begin{array}{ccc}
  \begin{bmatrix} 
    1  & -1 & 2 \\ 
    3  & 1 & 2 \\
    2  & 3 & -1
  \end{bmatrix} & \,\,\,\,\,\, &
  \begin{bmatrix} 
    2  & 3 & 0 \\ 
    1  &-2 &-1 \\
    2  & 0 &-1
  \end{bmatrix} \\
    \begin{bmatrix} 
    1  & 1 & 0 \\ 
    1  & 0 & 1 \\
    0  & 1 & 1
  \end{bmatrix} & \,\,\,\,\,\, &
  \begin{bmatrix} 
    a  & 0 & 0 \\ 
    1  & a & 0 \\
    0  & 1 & a
  \end{bmatrix}
\end{array}
\end{equation*}

14. Demostrar que si $A$ es invertible y simérica entonces $A^{-1}$ también es simétrica.

15. Si $A$ es una matriz cuadrada de tamaño $n$, tal que $\mathbf{I}-A$ es invertible, probar que 
\[
A(\mathbf{I}-A)^{-1} = (\mathbf{I}-A)^{-1}A
\]
\newpage

# Regla de Cramer

1. Usa la regla de Cramer para resolver los siguientes sistemas de
ecuaciones:

\begin{multicols}{2}
\begin{equation*}
\begin{array}{cccccc}
x & + y &+ z &- w & = & 2  \\
  &   y &- z &+w  & = & 1  \\
  &     &  z &-w  & = & 0  \\
  &     &  z &+2w & = & 3
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
x & +y & +z & = & a \\
  & y  & +z & = & 0 \\
  &    & z  & = & 1 \\
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
x & + y &+ z  & = & 11  \\
2x& -6y &- z  & = & 0  \\
3x& +4y &+2z  & = & 0  
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
x & +2y & +3z & = & 7 \\
2x& +y  & +2z & = & 0 \\
-2x&+y  & -z  & = & 4 
\end{array}
\end{equation*}
\end{multicols}

2. Usando la fórmula de la adjunta calcula la inversa de las siguientes
matrices:

\begin{multicols}{2}
\begin{equation*}
\begin{array}{ccccc}
1) A=& 
  \begin{pmatrix} 
    -2       & 3      & 2           \\ 
     6       & 0      & 3           \\
     4       & 1      & -1     
  \end{pmatrix}
 & \,\,\,\,\, &
2) B=&  \begin{pmatrix} 
     \cos\theta       & 0      & -\mbox{sen}\theta    \\ 
       0              & 1      & 0           \\
    \mbox{sen}\theta  & 0      & \cos\theta     
  \end{pmatrix}
\end{array}
\end{equation*}

\begin{equation*}
\begin{array}{ccccc}
3) A=& 
  \begin{vmatrix} 
     1       & 2      & -1           \\ 
     0       & 1      & 3           \\
     2       & 3      & -3     
  \end{vmatrix}
 & \,\,\,\,\, &
4) A=&  \begin{vmatrix} 
     2       & 4      & -1           \\ 
     1       & -1     & 3           \\
     3       & 4      & -3   
  \end{vmatrix}
\end{array}
\end{equation*}
\end{multicols}

3. Determinar las condiciones sobre \(a\) y \(b\) tal que el sistema
\begin{equation*}
  \begin{array}{cccc}
     x   & + y   & -a z    &= 1  \\
     2 x & +3 y  & 2z      & = b\\
     x   & -y    & +bz     & =a
  \end{array}
\end{equation*}

4. Aplicando la regla de Cramer, indica todos los valores de \(a\)
tales que la solución del siguiente sistema \emph{no} sea única.
\begin{equation*}
\begin{array}{cccccc}
(8-a)x & +2y      & +3z & +aw  & = & 0 \\
     x & +(9-a)y  & +4z & + aw & = & 0 \\
     x & +2y      & +3z & + aw & = & 0 \\
     x & +2y      & +3z & + aw & = & 0
\end{array}
\end{equation*}

Para el siguiente sistema de ecuaciones lineales 
\begin{equation*}
  \begin{array}{cccccc}
       x_1 & -  & 2x_2 & +  &  ax_3    & = 1  \\
     3 x_1 & +  & 2x_2 & +  &  x_3    & = 2\\
     2 x_1 &    &      &  + &  ax_3    & = 3
  \end{array}
\end{equation*}

a) Usando la regla de Cramer, resolver el sistema para a = 2

b) Encontrar los valores para los cuales el sistema tiene una infinidad de soluciones.