---
title: "Tarea 1"
author: "álgebra lineal"
date: "2024-09-14"
output:
  pdf_document:
  header-includes:
      - \usepackage{amsmath}
      - \usepackage{multicols}
---
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

# Vectores 


# Rectas y planos


# Sistemas de ecuaciones

1. Considere los siguientes sistemas de ecuaciones lineales:
\[
\begin{array}{cc}
  2x_1 + 3x_2 &= 5 \\
  x_1  - 4x_2 &= -3 \\
  2x_1 - 8x_2 & = -6
\end{array} 
\quad \quad \quad
\begin{array}{cc}
  2x_1 + 3x_2 &= 5 \\
  x_1  - 4x_2 &= -3 
\end{array}
\]
Determine el conjunto solución de cada uno de los sistemas ¿Son sistemas equivalentes?


# Matrices


1. Calcula los productos $ABC$ y $BA$ de las matrices, con 
\[
\begin{array}{lcr}
A=\begin{pmatrix}
    991 & 992 & 993 \\
    994 & 995 & 996 \\
    997 & 998 & 999
  \end{pmatrix}, \quad &
B = \begin{pmatrix}
    12 & -6 & -2 \\
    18 & -9 & -3 \\
    24 &-12 & -4
    \end{pmatrix}, \quad &
C = \begin{pmatrix}
    1 & 1  \\
    1 & 2  \\
    3 & 0 
    \end{pmatrix}
\end{array}
\]

1. a) Una matriz se dice *idempotente* si $A^2 = A$. Probar que
\[
B= \begin{pmatrix}
    2 & -3 & -5 \\
   -1 &  4 & 5  \\
    1 & -3 &- 4
   \end{pmatrix}
\]
es idempotente
 b) Demuestre qu si $A$ es idempotente, entonces $B=I_n-A$ también es idempotente,
 c) Si $A$ y $B$ son como en b) entonces demuestre que $AB= BA = \mathbf{0}$ 

1. Se dice que una matriz $n\times n$ es *involutiva* si y sólo si $A^2 = I_n$.
  
  a) Verifica que $A=\begin{pmatrix} 0 & 1 & -1 \\ 4 & -3 & 4 \\ 3 & -3 & 4 \end{pmatrix}$ es involutiva
  
  b) Demuestre que si $A$ es involutiva entonces $\frac{1}{2}(I_n+A)$ y $\frac{1}{2}(I_n-A)$ son idempotentes y su producto es igual a la matriz cero.
  
1- Para las siguientes matrices, encontrar la fórmula para $A^{n}$ con $n\in\mathbb{N}$,

\[
\begin{multicols}{2}
 A= \begin{pmatrix}
    \cos x       & -\mbox{sen} x \\
    \mbox{sen} x & \cos x
    \end{pmatrix} &
    
A= \begin{pmatrix}
    a       & 1 \\
    0       & a
    \end{pmatrix} 
\end{multicols}
\]